[server]
address = ":8888"
log_level = "info"
fetch_timeout = "30s"

[cache]
enabled = true
type = "disk"

[cache.disk]
path = "/tmp/toru-cache"

# [cache.s3]
# region = "us-west-2"
# bucket = "my-go-proxy-cache"
# access_key = "YOUR_ACCESS_KEY"
# secret_key = "YOUR_SECRET_KEY"

[auth]
enabled = false

[auth.modules]
name = "gitlab"
type = "gitlab_access_token"
options.root_url = "https://gitlab.corp.tech"
options.protected_uri = "corp.tech"

[[rewrite_rules]]
vanity_path = "example.com/mymodule"
target_path = "github.com/example/mymodule"
